Emily development
codeu-spring2018-team14/codeu_project_2018 pull request #5
Opened 2018-03-20 23:19 UTC by emilybpadgett

This is for step 1 of Project 1. I added a password to the User class and updated all of the tests that use User.

2018-03-21 01:19 UTC, alondarobichaud approved these changes

2018-03-22 01:51 UTC, tsums requested changes
Can you give the pull request a more meaningful description?

2018-03-22 01:51 UTC, tsums commented on src/main/java/codeu/controller/LoginServlet.java
> +//TODO: add password
Give this the same amount of indentation as the code under the `if` statement.

2018-03-22 01:51 UTC, tsums commented on src/main/java/codeu/model/store/persistence/PersistentDataStore.java
> +//TODO: get password from Datastore
Give this the same amount of indentation as the surrounding code.

2018-03-27 20:38 UTC, tsums approved these changes

2018-03-28 20:23 UTC, merged